### PR TITLE
Add alwaysFireHandler property to have shortcuts in focused inputs

### PR DESCRIPTION
**Pull request by Dunkat**

### CODE REVIEW

**Comment by cadavre** [comment]
Is this PR related to #10 ?

**Comment by damianprzygodzki** [comment]
Clean and needed solution.

**Comment by cadavre** [comment]
@petrbrzek ?

**Comment by petrbrzek** [comment]
I meant it differently. My proposal was to add custom data attribute to desired input as is shown below and handle this case internally inside `<Shortcuts>` component.
 
```
const Test = (props) => {
  return (
    <Shortcuts
      name={props.name}
      onHandler={props.handler}
    >
      <input type='text' onChange={props.onChange} dataShortcuts />
    </Shortcuts>
  )
}
```

This will be handled in `<Shortcuts>` like this :

```
    this._combokeys.stopCallback = (event, domElement, combo) => {
      const isInputLikeElement = domElement.tagName === 'INPUT' ||
        domElement.tagName === 'SELECT' || domElement.tagName === 'TEXTAREA' ||
          (domElement.contentEditable && domElement.contentEditable === 'true')

      const dataShortcuts = domElement.dataset.shortcuts
    
      let isReturnString
      if (event.key) {
        isReturnString = (event.key.length === 1)
      } else {
        isReturnString = Boolean(helpers.getCharacter(event))
      }

      if (isInputLikeElement && isReturnString && !dataShortcuts) {
        return true
      }

      return false
    }
```

What do you think? Would you rather specify the attribute in inputs or as a prop in `<Shortcuts>`.

**Comment by Dunkat** [comment]
It would be good solution but not in case when you have a lot of inputs, then you need specyfy property in each single input. So maybe it's better to have it in prop.

Another case when you have a few types of Shortcuts e.g 'globals', and you need only this one working in inputs. 

I think prop in Shortcuts is more flexible, but it's my opinion :)

**Comment by petrbrzek** [comment]
@Dunkat I don't a problem with the prop. I just think it should be named better. Maybe something like `alwaysFireHandler={true}`. Also there should be test case for it.

**Comment by Dunkat** [comment]
Sure,  I will change the name on 'alwaysFireHandler'.

**Comment by Dunkat** [comment]
@petrbrzek about test case, should I add this to test/shortcuts.spec.js ? Something like 

`it('should fire the handler', () => {
   ...
    expect(wrapper.props().handler).to.have.been.called
  })`

**Comment by petrbrzek** [comment]
@Dunkat You should create a dummy component with an input wrapped by `<Shortcuts>`. Then you should simulate a key event from the input [that key should match some specified shortcut from the keymap (could be a single char) to fire the handler] and this should pass at the end of the test`expect(wrapper.props().handler).to.have.been.called`.

**Comment by Dunkat** [comment]
@petrbrzek please have a look. Test case added and prop name changed

**Comment by petrbrzek** [comment]
@Dunkat I like it. 👍

**Comment by petrbrzek** [comment]
React Shortcuts 1.4.0 was released on NPM.

**Pull request merged**
