### PR TITLE
replace shortcuts with div

### LINKED ISSUE #39: Unrecognized tag: shortcuts
The [shortcuts component](https://github.com/avocode/react-shortcuts/blob/master/src/component/shortcuts.js#L222) uses a `<shortcuts>` tag to wrap the children. As a result, I get the following error from React:

> Warning: The tag <shortcuts> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.

Is there a reason this isn't a div or some other recognized tag? Can it just be a div with maybe a shortcuts class?

I'm running React 16 rc3, and I've seen this message since rc1. Other than that message, everything seems to work great in v16.

### PR DESCRIPTION
**Pull request by Asp3ctus**
Fixes #39

### CODE REVIEW

**Comment by w33ble** [comment]
Now that React v16 is released, it would be great to see this merged.

**Comment by petrbrzek** [comment]
@Asp3ctus Thanks.

**Comment by subvertallchris** [comment]
Thanks for getting this fixed. Could you do a release to npm that includes it?

**Comment by pmusaraj** [comment]
@dcosson I ran into the same issue, and the solution was to update the version in `package.json`: 

````
"react-shortcuts": "^2.0.0",
````

**Pull request merged**
